name: Puzzles HQ workflow

on:
  release:
    types: [published]

jobs:
  edit-manifest:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Pull Versioning API
        run: "git clone https://github.com/PuzzlesHQ/versioning-spec"
      - name: Update dirs
        run: "cp -r versioning-spec versioning"
      - name: Edit Version Manifest
        run: python versioning/main.py
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GH_TOKEN: ${{ github.token }}

  publish-release:
    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/maven-publishing-notag.yml@main
    secrets: inherit
    with:
      TAG_NAME: ${{ github.event.release.tag_name }}